#!/usr/bin/env python3
"""Generate checked-in Noria container reference-model fixtures.

Emits opcode/argument tables and a compact interpreter loop so CTest never
needs to regenerate sources. Use --check to verify committed files match.
"""

from __future__ import annotations

import argparse
import hashlib
import heapq
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "examples" / "basic"

MODEL_VERSION = "1"
OPS = 300
CHECKPOINT_EVERY = 50

# Sequence opcodes
S_PUSH, S_INSERT, S_SET, S_REMOVE, S_POP, S_CLONE_PUSH = range(6)
# Dictionary opcodes
D_INSERT, D_OVERWRITE, D_REMOVE, D_LOOKUP, D_CLONE_INSERT = range(5)
# Set opcodes
Z_INSERT, Z_REMOVE, Z_CONTAINS, Z_CLONE_INSERT = range(4)
# Heap opcodes
H_PUSH, H_POP = range(2)


def fmt_i32_array(name: str, values: list[int]) -> str:
    body = ", ".join(str(int(v)) for v in values)
    return f"  let {name}: [i32] = [{body}];"


def header(kind: str, seed: int) -> str:
    digest = hashlib.sha256(f"{kind}:{MODEL_VERSION}:{seed}:{OPS}".encode()).hexdigest()[:16]
    return "\n".join(
        [
            f"// Generated by tools/generate_container_models.py — do not edit by hand.",
            f"// model: {kind}  version: {MODEL_VERSION}  seed: {seed}  ops: {OPS}",
            f"// fingerprint: {digest}",
            "",
        ]
    )


def fail_print(msg: str) -> str:
    return f'    print("{msg}");\n    print_int(i);\n    println();\n'


class Rng:
    """Deterministic LCG."""

    def __init__(self, seed: int) -> None:
        self.state = seed & 0xFFFFFFFF

    def next_u32(self) -> int:
        self.state = (1664525 * self.state + 1013904223) & 0xFFFFFFFF
        return self.state

    def randint(self, lo: int, hi: int) -> int:
        if hi < lo:
            raise ValueError("hi < lo")
        span = hi - lo + 1
        return lo + int(self.next_u32() % span)


def gen_sequence(seed: int = 0xC0FFEE01) -> str:
    rng = Rng(seed)
    model: list[int] = []
    ops: list[int] = []
    a0: list[int] = []
    a1: list[int] = []
    # Checkpoint payloads: len + fingerprint (sum (i+1)*v)
    ck_len: list[int] = []
    ck_fp: list[int] = []

    def fingerprint(xs: list[int]) -> int:
        total = 0
        for i, v in enumerate(xs):
            total = (total + (i + 1) * v) & 0x7FFFFFFF
        return total

    def record_checkpoint() -> None:
        ck_len.append(len(model))
        ck_fp.append(fingerprint(model))

    # Emphasize front/middle shifting early.
    for i in range(OPS):
        if i > 0 and i % CHECKPOINT_EVERY == 0:
            record_checkpoint()

        if not model:
            op = S_PUSH
        else:
            op = rng.randint(0, 5)

        if op == S_PUSH:
            val = rng.randint(0, 97)
            model.append(val)
            ops.append(S_PUSH)
            a0.append(val)
            a1.append(0)
        elif op == S_INSERT:
            idx = rng.randint(0, len(model))
            val = rng.randint(0, 97)
            model.insert(idx, val)
            ops.append(S_INSERT)
            a0.append(idx)
            a1.append(val)
        elif op == S_SET:
            idx = rng.randint(0, len(model) - 1)
            val = rng.randint(0, 97)
            model[idx] = val
            ops.append(S_SET)
            a0.append(idx)
            a1.append(val)
        elif op == S_REMOVE:
            idx = rng.randint(0, len(model) - 1)
            model.pop(idx)
            ops.append(S_REMOVE)
            a0.append(idx)
            a1.append(0)
        elif op == S_POP:
            model.pop()
            ops.append(S_POP)
            a0.append(0)
            a1.append(0)
        else:  # S_CLONE_PUSH — clone then diverge; model tracks primary only after restore
            # Encode: push val onto a clone; primary unchanged. Verified in Noria via clone path.
            val = rng.randint(0, 97)
            ops.append(S_CLONE_PUSH)
            a0.append(val)
            a1.append(len(model))  # expected primary length after clone divergence
            # model unchanged

    record_checkpoint()

    lines = [
        header("sequence", seed),
        "import std::sequence::{Sequence, sequence_get, sequence_insert, sequence_len, sequence_new,",
        "                       sequence_pop, sequence_push, sequence_remove, sequence_set};",
        "",
        "fn fingerprint(s: Sequence<i32, arr>) -> i32 {",
        "  let total: i32 = 0;",
        "  let i: i32 = 0;",
        "  while i < sequence_len(s) {",
        "    total = total + (i + 1) * sequence_get(s, i);",
        "    i = i + 1;",
        "  }",
        "  return total;",
        "}",
        "",
        "fn fingerprint_list(s: Sequence<i32, list>) -> i32 {",
        "  let total: i32 = 0;",
        "  let i: i32 = 0;",
        "  while i < sequence_len(s) {",
        "    total = total + (i + 1) * sequence_get(s, i);",
        "    i = i + 1;",
        "  }",
        "  return total;",
        "}",
        "",
        "fn run_arr() -> i32 {",
        "  let s: Sequence<i32, arr> = sequence_new(0);",
        fmt_i32_array("ops", ops),
        fmt_i32_array("a0", a0),
        fmt_i32_array("a1", a1),
        fmt_i32_array("ck_len", ck_len),
        fmt_i32_array("ck_fp", ck_fp),
        "  let ck: i32 = 0;",
        f"  let i: i32 = 0;",
        f"  while i < {OPS} {{",
        "    if i > 0 && i % 50 == 0 {",
        "      if sequence_len(s) != ck_len[ck] {",
        fail_print("sequence arr checkpoint len mismatch at op "),
        "        return 10 + ck;",
        "      }",
        "      if fingerprint(s) != ck_fp[ck] {",
        fail_print("sequence arr checkpoint fingerprint mismatch at op "),
        "        return 20 + ck;",
        "      }",
        "      ck = ck + 1;",
        "    }",
        "    let op: i32 = ops[i];",
        "    if op == 0 {",
        "      sequence_push(s, a0[i]);",
        "    } else if op == 1 {",
        "      sequence_insert(s, a0[i], a1[i]);",
        "    } else if op == 2 {",
        "      sequence_set(s, a0[i], a1[i]);",
        "    } else if op == 3 {",
        "      let removed: i32 = sequence_remove(s, a0[i]);",
        "      if removed == -999999 {",
        "        return 30;",
        "      }",
        "    } else if op == 4 {",
        "      let popped: i32 = sequence_pop(s);",
        "      if popped == -999999 {",
        "        return 31;",
        "      }",
        "    } else {",
        "      let copy: Sequence<i32, arr> = s;",
        "      sequence_push(copy, a0[i]);",
        "      if sequence_len(s) != a1[i] {",
        fail_print("sequence arr clone divergence failed at op "),
        "        return 40;",
        "      }",
        "      if sequence_len(copy) != a1[i] + 1 {",
        fail_print("sequence arr clone length failed at op "),
        "        return 41;",
        "      }",
        "    }",
        "    i = i + 1;",
        "  }",
        "  if sequence_len(s) != ck_len[ck] {",
        '    print("sequence arr final len mismatch");',
        "    println();",
        "    return 50;",
        "  }",
        "  if fingerprint(s) != ck_fp[ck] {",
        '    print("sequence arr final fingerprint mismatch");',
        "    println();",
        "    return 51;",
        "  }",
        "  return 0;",
        "}",
        "",
        "fn run_list() -> i32 {",
        "  let s: Sequence<i32, list> = sequence_new(0);",
        fmt_i32_array("ops", ops),
        fmt_i32_array("a0", a0),
        fmt_i32_array("a1", a1),
        fmt_i32_array("ck_len", ck_len),
        fmt_i32_array("ck_fp", ck_fp),
        "  let ck: i32 = 0;",
        "  let i: i32 = 0;",
        f"  while i < {OPS} {{",
        "    if i > 0 && i % 50 == 0 {",
        "      if sequence_len(s) != ck_len[ck] {",
        fail_print("sequence list checkpoint len mismatch at op "),
        "        return 60 + ck;",
        "      }",
        "      if fingerprint_list(s) != ck_fp[ck] {",
        fail_print("sequence list checkpoint fingerprint mismatch at op "),
        "        return 70 + ck;",
        "      }",
        "      ck = ck + 1;",
        "    }",
        "    let op: i32 = ops[i];",
        "    if op == 0 {",
        "      sequence_push(s, a0[i]);",
        "    } else if op == 1 {",
        "      sequence_insert(s, a0[i], a1[i]);",
        "    } else if op == 2 {",
        "      sequence_set(s, a0[i], a1[i]);",
        "    } else if op == 3 {",
        "      let removed: i32 = sequence_remove(s, a0[i]);",
        "      if removed == -999999 {",
        "        return 80;",
        "      }",
        "    } else if op == 4 {",
        "      let popped: i32 = sequence_pop(s);",
        "      if popped == -999999 {",
        "        return 81;",
        "      }",
        "    } else {",
        "      let copy: Sequence<i32, list> = s;",
        "      sequence_push(copy, a0[i]);",
        "      if sequence_len(s) != a1[i] {",
        fail_print("sequence list clone divergence failed at op "),
        "        return 90;",
        "      }",
        "      if sequence_len(copy) != a1[i] + 1 {",
        fail_print("sequence list clone length failed at op "),
        "        return 91;",
        "      }",
        "    }",
        "    i = i + 1;",
        "  }",
        "  if sequence_len(s) != ck_len[ck] {",
        '    print("sequence list final len mismatch");',
        "    println();",
        "    return 100;",
        "  }",
        "  if fingerprint_list(s) != ck_fp[ck] {",
        '    print("sequence list final fingerprint mismatch");',
        "    println();",
        "    return 101;",
        "  }",
        "  return 0;",
        "}",
        "",
        "fn main() -> i32 {",
        "  let r: i32 = run_arr();",
        "  if r != 0 {",
        "    return r;",
        "  }",
        "  return run_list();",
        "}",
        "",
    ]
    return "\n".join(lines)


def gen_dictionary(seed: int = 0xC0FFEE02) -> str:
    rng = Rng(seed)
    model: dict[int, int] = {}
    ops: list[int] = []
    a0: list[int] = []
    a1: list[int] = []
    ck_len: list[int] = []

    def record_checkpoint() -> None:
        ck_len.append(len(model))

    planned: list[tuple[int, int, int]] = []
    # Prelude: two-child BST deletion (remove root 4 with children).
    planned.extend(
        [
            (D_INSERT, 4, 40),
            (D_INSERT, 2, 20),
            (D_INSERT, 6, 60),
            (D_INSERT, 1, 10),
            (D_INSERT, 3, 30),
            (D_INSERT, 5, 50),
            (D_INSERT, 7, 70),
            (D_REMOVE, 4, 40),
        ]
    )
    # Force hashmap resize then tombstone reuse.
    for k in range(100, 140):
        planned.append((D_INSERT, k, k * 3))
    for k in range(100, 120):
        planned.append((D_REMOVE, k, k * 3))
    for k in range(100, 120):
        planned.append((D_INSERT, k, k * 5))

    while len(planned) < OPS:
        shadow: dict[int, int] = {}
        for op, k, v in planned:
            if op in (D_INSERT, D_OVERWRITE):
                shadow[k] = v
            elif op == D_REMOVE:
                shadow.pop(k, None)
        if not shadow:
            key = rng.randint(0, 200)
            planned.append((D_INSERT, key, rng.randint(0, 500)))
            continue
        op = rng.randint(0, 4)
        if op == D_INSERT:
            key = rng.randint(0, 200)
            while key in shadow:
                key = rng.randint(0, 250)
            planned.append((D_INSERT, key, rng.randint(0, 500)))
        elif op == D_OVERWRITE:
            keys = list(shadow.keys())
            key = keys[rng.randint(0, len(keys) - 1)]
            planned.append((D_OVERWRITE, key, rng.randint(0, 500)))
        elif op == D_REMOVE:
            keys = list(shadow.keys())
            key = keys[rng.randint(0, len(keys) - 1)]
            planned.append((D_REMOVE, key, shadow[key]))
        elif op == D_LOOKUP:
            keys = list(shadow.keys())
            key = keys[rng.randint(0, len(keys) - 1)]
            planned.append((D_LOOKUP, key, shadow[key]))
        else:
            key = rng.randint(100000, 200000)
            while key in shadow:
                key = rng.randint(100000, 200000)
            planned.append((D_CLONE_INSERT, key, rng.randint(0, 500)))

    planned = planned[:OPS]
    model = {}
    for i, (op, k, v) in enumerate(planned):
        if i > 0 and i % CHECKPOINT_EVERY == 0:
            record_checkpoint()
        ops.append(op)
        a0.append(k)
        a1.append(v)
        if op in (D_INSERT, D_OVERWRITE):
            model[k] = v
        elif op == D_REMOVE:
            del model[k]
        # lookup / clone leave primary unchanged
    record_checkpoint()

    def emit_run(tag: str, base_err: int) -> list[str]:
        ty = f"Dictionary<i32, i32, {tag}>"
        return [
            f"fn run_{tag}() -> i32 {{",
            f"  let d: {ty} = dictionary_new(0, 0);",
            fmt_i32_array("ops", ops),
            fmt_i32_array("a0", a0),
            fmt_i32_array("a1", a1),
            fmt_i32_array("ck_len", ck_len),
            "  let ck: i32 = 0;",
            "  let i: i32 = 0;",
            f"  while i < {OPS} {{",
            "    if i > 0 && i % 50 == 0 {",
            "      if dictionary_len(d) != ck_len[ck] {",
            fail_print(f"dictionary {tag} checkpoint len mismatch at op "),
            f"        return {base_err} + ck;",
            "      }",
            "      ck = ck + 1;",
            "    }",
            "    let op: i32 = ops[i];",
            "    if op == 0 || op == 1 {",
            "      dictionary_insert(d, a0[i], a1[i]);",
            "    } else if op == 2 {",
            "      let removed: i32 = dictionary_remove(d, a0[i]);",
            "      if removed != a1[i] {",
            fail_print(f"dictionary {tag} remove value mismatch at op "),
            f"        return {base_err + 20};",
            "      }",
            "    } else if op == 3 {",
            "      if dictionary_get(d, a0[i]) != a1[i] {",
            fail_print(f"dictionary {tag} lookup mismatch at op "),
            f"        return {base_err + 30};",
            "      }",
            "    } else {",
            f"      let copy: {ty} = d;",
            "      dictionary_insert(copy, a0[i], a1[i]);",
            "      if dictionary_contains(d, a0[i]) {",
            fail_print(f"dictionary {tag} clone polluted primary at op "),
            f"        return {base_err + 40};",
            "      }",
            "      if !dictionary_contains(copy, a0[i]) {",
            fail_print(f"dictionary {tag} clone missing key at op "),
            f"        return {base_err + 41};",
            "      }",
            "    }",
            "    i = i + 1;",
            "  }",
            "  if dictionary_len(d) != ck_len[ck] {",
            f'    print("dictionary {tag} final len mismatch");',
            '    println();',
            f"    return {base_err + 50};",
            "  }",
            "  return 0;",
            "}",
            "",
        ]

    lines = [
        header("dictionary", seed),
        "import std::dictionary::{Dictionary, dictionary_contains, dictionary_get, dictionary_insert,",
        "                         dictionary_len, dictionary_new, dictionary_remove};",
        "",
    ]
    lines.extend(emit_run("bst", 10))
    lines.extend(emit_run("hashmap", 110))
    lines.extend(
        [
            "fn main() -> i32 {",
            "  let r: i32 = run_bst();",
            "  if r != 0 {",
            "    return r;",
            "  }",
            "  return run_hashmap();",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def gen_set(seed: int = 0xC0FFEE03) -> str:
    rng = Rng(seed)
    model: set[int] = set()
    ops: list[int] = []
    a0: list[int] = []
    a1: list[int] = []
    ck_len: list[int] = []

    def record_checkpoint() -> None:
        ck_len.append(len(model))

    for i in range(OPS):
        if i > 0 and i % CHECKPOINT_EVERY == 0:
            record_checkpoint()

        if not model:
            op = Z_INSERT
        else:
            op = rng.randint(0, 3)

        if op == Z_INSERT:
            val = rng.randint(0, 80)
            before = len(model)
            model.add(val)
            ops.append(Z_INSERT)
            a0.append(val)
            a1.append(1 if len(model) > before else 0)  # 1 = newly inserted
        elif op == Z_REMOVE:
            vals = list(model)
            val = vals[rng.randint(0, len(vals) - 1)]
            model.remove(val)
            ops.append(Z_REMOVE)
            a0.append(val)
            a1.append(0)
        elif op == Z_CONTAINS:
            if rng.randint(0, 1) == 0 and model:
                val = list(model)[rng.randint(0, len(model) - 1)]
                expect = 1
            else:
                val = rng.randint(200, 300)
                expect = 1 if val in model else 0
            ops.append(Z_CONTAINS)
            a0.append(val)
            a1.append(expect)
        else:
            val = rng.randint(1000, 2000)
            while val in model:
                val = rng.randint(1000, 2000)
            ops.append(Z_CLONE_INSERT)
            a0.append(val)
            a1.append(len(model))
    record_checkpoint()

    def emit_run(tag: str, base_err: int) -> list[str]:
        ty = f"Set<i32, {tag}>"
        return [
            f"fn run_{tag}() -> i32 {{",
            f"  let s: {ty} = set_new(0);",
            fmt_i32_array("ops", ops),
            fmt_i32_array("a0", a0),
            fmt_i32_array("a1", a1),
            fmt_i32_array("ck_len", ck_len),
            "  let ck: i32 = 0;",
            "  let i: i32 = 0;",
            f"  while i < {OPS} {{",
            "    if i > 0 && i % 50 == 0 {",
            "      if set_len(s) != ck_len[ck] {",
            fail_print(f"set {tag} checkpoint len mismatch at op "),
            f"        return {base_err} + ck;",
            "      }",
            "      ck = ck + 1;",
            "    }",
            "    let op: i32 = ops[i];",
            "    if op == 0 {",
            "      set_insert(s, a0[i]);",
            "    } else if op == 1 {",
            "      set_remove(s, a0[i]);",
            "    } else if op == 2 {",
            "      let present: bool = set_contains(s, a0[i]);",
            "      if present && a1[i] == 0 {",
            fail_print(f"set {tag} unexpected contains at op "),
            f"        return {base_err + 20};",
            "      }",
            "      if !present && a1[i] != 0 {",
            fail_print(f"set {tag} missing contains at op "),
            f"        return {base_err + 21};",
            "      }",
            "    } else {",
            f"      let copy: {ty} = s;",
            "      set_insert(copy, a0[i]);",
            "      if set_len(s) != a1[i] {",
            fail_print(f"set {tag} clone polluted primary at op "),
            f"        return {base_err + 40};",
            "      }",
            "      if set_len(copy) != a1[i] + 1 {",
            fail_print(f"set {tag} clone length failed at op "),
            f"        return {base_err + 41};",
            "      }",
            "    }",
            "    i = i + 1;",
            "  }",
            "  if set_len(s) != ck_len[ck] {",
            f'    print("set {tag} final len mismatch");',
            '    println();',
            f"    return {base_err + 50};",
            "  }",
            "  return 0;",
            "}",
            "",
        ]

    lines = [
        header("set", seed),
        "import std::set::{Set, set_contains, set_insert, set_len, set_new, set_remove};",
        "",
    ]
    lines.extend(emit_run("bst", 10))
    lines.extend(emit_run("hashmap", 110))
    lines.extend(
        [
            "fn main() -> i32 {",
            "  let r: i32 = run_bst();",
            "  if r != 0 {",
            "    return r;",
            "  }",
            "  return run_hashmap();",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def gen_heap(seed: int = 0xC0FFEE04) -> str:
    rng = Rng(seed)
    model: list[int] = []
    ops: list[int] = []
    a0: list[int] = []
    ck_len: list[int] = []
    ck_min: list[int] = []

    def record_checkpoint() -> None:
        ck_len.append(len(model))
        ck_min.append(model[0] if model else -1)

    for i in range(OPS):
        if i > 0 and i % CHECKPOINT_EVERY == 0:
            record_checkpoint()

        if not model:
            op = H_PUSH
        else:
            op = rng.randint(0, 1)

        if op == H_PUSH:
            val = rng.randint(0, 500)
            heapq.heappush(model, val)
            ops.append(H_PUSH)
            a0.append(val)
        else:
            expected = heapq.heappop(model)
            ops.append(H_POP)
            a0.append(expected)
    record_checkpoint()

    def emit_run(tag: str, base_err: int) -> list[str]:
        return [
            f"fn run_{tag}() -> i32 {{",
            f"  let s: Sequence<i32, {tag}> = sequence_new(0);",
            fmt_i32_array("ops", ops),
            fmt_i32_array("a0", a0),
            fmt_i32_array("ck_len", ck_len),
            fmt_i32_array("ck_min", ck_min),
            "  let ck: i32 = 0;",
            "  let i: i32 = 0;",
            f"  while i < {OPS} {{",
            "    if i > 0 && i % 50 == 0 {",
            "      if sequence_len(s) != ck_len[ck] {",
            fail_print(f"heap {tag} checkpoint len mismatch at op "),
            f"        return {base_err} + ck;",
            "      }",
            "      if ck_len[ck] > 0 && sequence_get(s, 0) != ck_min[ck] {",
            fail_print(f"heap {tag} checkpoint min mismatch at op "),
            f"        return {base_err + 10} + ck;",
            "      }",
            "      ck = ck + 1;",
            "    }",
            "    let op: i32 = ops[i];",
            "    if op == 0 {",
            "      heappush(s, a0[i]);",
            "    } else {",
            "      let got: i32 = heappop(s);",
            "      if got != a0[i] {",
            fail_print(f"heap {tag} pop mismatch at op "),
            f"        return {base_err + 30};",
            "      }",
            "    }",
            "    i = i + 1;",
            "  }",
            "  if sequence_len(s) != ck_len[ck] {",
            f'    print("heap {tag} final len mismatch");',
            '    println();',
            f"    return {base_err + 50};",
            "  }",
            "  return 0;",
            "}",
            "",
        ]

    lines = [
        header("heap", seed),
        "import std::heap::{heappop, heappush};",
        "import std::sequence::{Sequence, sequence_get, sequence_len, sequence_new};",
        "",
    ]
    lines.extend(emit_run("arr", 10))
    lines.extend(emit_run("list", 110))
    lines.extend(
        [
            "fn main() -> i32 {",
            "  let r: i32 = run_arr();",
            "  if r != 0 {",
            "    return r;",
            "  }",
            "  return run_list();",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


FIXTURES = {
    "container_model_sequence.noria": gen_sequence,
    "container_model_dictionary.noria": gen_dictionary,
    "container_model_set.noria": gen_set,
    "container_model_heap.noria": gen_heap,
}


def write_all() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, gen in FIXTURES.items():
        path = OUT_DIR / name
        path.write_text(gen())
        print(f"wrote {path.relative_to(ROOT)}")


def check_all() -> int:
    status = 0
    for name, gen in FIXTURES.items():
        path = OUT_DIR / name
        expected = gen()
        if not path.is_file():
            print(f"missing {path}", file=sys.stderr)
            status = 1
            continue
        actual = path.read_text()
        if actual != expected:
            print(f"drift: {path.relative_to(ROOT)} does not match generator", file=sys.stderr)
            status = 1
        else:
            print(f"ok {path.relative_to(ROOT)}")
    return status


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify committed fixtures")
    args = parser.parse_args()
    if args.check:
        return check_all()
    write_all()
    return 0


if __name__ == "__main__":
    sys.exit(main())
